title=DigiSim

menu.file.name=File
menu.file.tootip=File menu
menu.file.mnemonic=VK_F

menu.file.open.name=Open Project ...
menu.file.open.tooltip=Opens a Project file
menu.file.open.icon=
menu.file.open.accelerator=control O
menu.file.open.mnemonic=VK_O

menu.file.openNewWindow.name=Open new window ...
menu.file.openNewWindow.tooltip=Opens a Project file in a new window
menu.file.openNewWindow.icon=
menu.file.openNewWindow.accelerator=control shift O
menu.file.openNewWindow.mnemonic=VK_N

menu.file.closeProject.name=Close Project
menu.file.closeProject.tooltip=Closes the current Project
menu.file.closeProject.icon=
menu.file.closeProject.accelerator=control W
menu.file.closeProject.mnemonic=VK_C

menu.file.quit.name=Quit
menu.file.quit.tooltip=Close the application
menu.file.quit.icon=
menu.file.quit.accelerator=control Q
menu.file.quit.mnemonic=VK_Q

button.ok=Yes
button.no=No
button.cancel=Cancel

main.quit.confirm.msg=Really close the Application?
main.quit.confirm.title=Close Application


main.error.openFile.message=Can't open file {}
main.error.openFile.title=File not opened