title=DigiSim

# File Menu
menu.file.name=File
menu.file.tootip=File menu
menu.file.mnemonic=VK_F

menu.file.open.name=Open Project ...
menu.file.open.tooltip=Opens a Project file
menu.file.open.icon=
menu.file.open.accelerator=control O
menu.file.open.mnemonic=VK_O

menu.file.openNewWindow.name=Open new window ...
menu.file.openNewWindow.tooltip=Opens a Project file in a new window
menu.file.openNewWindow.icon=
menu.file.openNewWindow.accelerator=control shift O
menu.file.openNewWindow.mnemonic=VK_N

menu.file.closeProject.name=Close Project
menu.file.closeProject.tooltip=Closes the current Project
menu.file.closeProject.icon=
menu.file.closeProject.accelerator=control W
menu.file.closeProject.mnemonic=VK_C

menu.file.quit.name=Quit
menu.file.quit.tooltip=Close the application
menu.file.quit.icon=
menu.file.quit.accelerator=control Q
menu.file.quit.mnemonic=VK_Q

# View Menu
menu.view.name=View
menu.view.tootip=View menu
menu.view.mnemonic=VK_V

menu.view.openScheme.name=Open Scheme
menu.view.openScheme.tooltip=Opens the selected Scheme
menu.view.openScheme.icon=
menu.view.openScheme.accelerator=control Q
menu.view.openScheme.mnemonic=VK_O

menu.view.closeScheme.name=Close Scheme
menu.view.closeScheme.tooltip=Close the current Scheme
menu.view.closeScheme.icon=
menu.view.closeScheme.accelerator=control Q
menu.view.closeScheme.mnemonic=VK_C

menu.view.zoomIn.name=Zoom in
menu.view.zoomIn.tooltip=Zooms into the current Scheme
menu.view.zoomIn.icon=
menu.view.zoomIn.accelerator=control PLUS
menu.view.zoomIn.mnemonic=VK_I

menu.view.zoomOut.name=Zoom out
menu.view.zoomOut.tooltip=Zooms out the current Scheme
menu.view.zoomOut.icon=
menu.view.zoomOut.accelerator=control MINUS
menu.view.zoomOut.mnemonic=VK_U

menu.view.zoomFit.name=Zoom fit to Window
menu.view.zoomFit.tooltip=Zooms the current Scheme to fit the window
menu.view.zoomFit.icon=
menu.view.zoomFit.accelerator=control shift F
menu.view.zoomFit.mnemonic=VK_F


# general buttons
button.ok=Yes
button.no=No
button.cancel=Cancel

# dialogs
main.quit.confirm.msg=Really close the Application?
main.quit.confirm.title=Close Application


main.error.openFile.message=Can't open file {}
main.error.openFile.title=File not opened

# document window
document.tab.close.tooltip=close this tab

document.tab.context.closeThis.name=Close
document.tab.context.closeThis.tooltip=Close this scheme
document.tab.context.closeThis.icon=
document.tab.context.closeThis.accelerator=
document.tab.context.closeThis.mnemonic=

document.tab.context.closeOther.name=Close other
document.tab.context.closeOther.tooltip=Close other schemes
document.tab.context.closeOther.icon=
document.tab.context.closeOther.accelerator=
document.tab.context.closeOther.mnemonic=

document.tab.context.closeAll.name=Close all
document.tab.context.closeAll.tooltip=Close all schemes
document.tab.context.closeAll.icon=
document.tab.context.closeAll.accelerator=
document.tab.context.closeAll.mnemonic=

